language: c
compiler: gcc
services: docker
before_install:
  - docker build -t bennetschubert/pdfdiff .
install: skip
script:
  - docker run --rm --mount type=bind,source="$(pwd)"/src/,target=/src/ -w /src -it bennetschubert/pdfdiff /bin/sh -c "make"
  - cd src && make
addons:
  apt:
    update: true
